#ifndef __DPDK_H
#define __DPDK_H

#include <rte_version.h>
#include <rte_ethdev.h>
#include <rte_mbuf_core.h>
#if RTE_VERSION > RTE_VERSION_NUM(21, 0, 0, 0)
#define PKT_RX_FDIR  RTE_MBUF_F_RX_FDIR
#define PKT_RX_FDIR_ID  RTE_MBUF_F_RX_FDIR_ID
#define PKT_RX_FDIR_FLX RTE_MBUF_F_RX_FDIR_FLX
#define PKT_RX_RSS_HASH  RTE_MBUF_F_RX_RSS_HASH
#define ETH_LINK_UP RTE_ETH_LINK_UP
#define ETH_LINK_DOWN RTE_ETH_LINK_DOWN
#define DEV_TX_OFFLOAD_VLAN_INSERT RTE_ETH_TX_OFFLOAD_VLAN_INSERT
#define DEV_TX_OFFLOAD_IPV4_CKSUM  RTE_ETH_TX_OFFLOAD_IPV4_CKSUM       
#define DEV_TX_OFFLOAD_UDP_CKSUM   RTE_ETH_TX_OFFLOAD_UDP_CKSUM        
#define DEV_TX_OFFLOAD_TCP_CKSUM   RTE_ETH_TX_OFFLOAD_TCP_CKSUM        
#define DEV_TX_OFFLOAD_SCTP_CKSUM  RTE_ETH_TX_OFFLOAD_SCTP_CKSUM       
#define DEV_TX_OFFLOAD_TCP_TSO     RTE_ETH_TX_OFFLOAD_TCP_TSO 
#endif
#endif
