#ifndef __STAT_H__
#define __STAT_H__
#define net_stats_tcp_tx()
#define net_stats_tx_drop(m)
#define net_stats_tx(m)
//#define net_stats_tx_drop()
#define net_stats_fin_rx()
#define net_stats_syn_rx()
//#define net_stats_tx()
#define net_stats_pkt_lost()
#define net_stats_rtt(p1,p2)
#define net_stats_ack_rt()
#define net_stats_push_rt()  
#define net_stats_fin_rt()
//#define net_stats_socket_error() 
#define net_stats_syn_rt() 
#define net_stats_tcp_drop() 
#define net_stats_http_error() 
#define net_stats_http_get()
#define net_stats_syn_tx()
#define net_stats_fin_tx()
#define net_stats_rst_tx()
#define net_stats_tcp_req()
#define net_stats_http_2xx()
#define net_stats_tcp_rsp()
//#define http_parse_response(data,len) return 0
#define net_stats_socket_dup()      do {} while (0)
#define net_stats_socket_error()    do {} while (0)
#define net_stats_socket_open()     do {} while (0)
#define net_stats_socket_close()    do {} while (0)
#define net_stats_rst_rx()    do {} while (0)
#endif
