#!/bin/bash
ARCH=x86_64
OS=ubuntu18.04
DISTRO=ubuntu1804
PYTHON_VERSION=3.8
PYTORCH_VERSION=1.13.1
NCCL_VERSION=2.9.9
CUDA_VERSION=11.3
OUT_IMAGES=fedml-x86
bash build-docker.sh $ARCH $OS $DISTRO $PYTHON_VERSION $PYTORCH_VERSION $NCCL_VERSION $CUDA_VERSION $OUT_IMAGES
