mgid = bfrt.pre.mgid
node = bfrt.pre.node

node.add(MULTICAST_NODE_ID=36,DEV_PORT=[36,68])
node.add(MULTICAST_NODE_ID=37,DEV_PORT=[44])

node.add(MULTICAST_NODE_ID=44,DEV_PORT=[44,68])
node.add(MULTICAST_NODE_ID=45,DEV_PORT=[36])

mgid.add(MGID=24,MULTICAST_NODE_ID=[36],MULTICAST_NODE_L1_XID=[37],MULTICAST_NODE_L1_XID_VALID=[False])
mgid.add(MGID=44,MULTICAST_NODE_ID=[44],MULTICAST_NODE_L1_XID=[45],MULTICAST_NODE_L1_XID_VALID=[False])
